"""GH #28 — Axlred's Berserk Dragon Slayer (Nexus mod 1455).

The mod is generated by CrimsonForge (github.com/hzeemr/crimsonforge)
in a format the generator calls ``mesh_loose_mod``:

    Berserk -The DragonSlayer/
    ├── manifest.json          format: "v1", kind: "mesh_loose_mod",
    │                          files_root: "files"
    ├── modinfo.json
    ├── README.txt
    ├── files/
    │   └── character/cd_phm_02_sword_0039.pac        (the mesh)
    └── Tex/
        └── Character/texture/
            ├── cd_phm_02_sword_0039.pac.xml          (texture binding)
            ├── cd_phm_02_sword_0039_disp.dds
            ├── cd_phm_02_sword_0039_ma.dds
            ├── cd_phm_02_sword_0039_mg.dds
            └── cd_phm_02_sword_0039_n.dds

Pre-fix CDUMM walked only ``files_dir`` (default "files") and silently
dropped everything in ``Tex/``. The mesh imported but the user saw
distorted textures because the 4 DDS files + texture-binding XML never
reached the game.

Fix extends ``convert_to_paz_mod`` to also scan sibling content dirs
named ``tex``/``textures``/``texture`` at the mod root, feeding their
files through the same basename-resolution + texture-overlay pipeline
that ``files_dir``'s unresolved bucket already uses.
"""
from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from cdumm.engine.crimson_browser_handler import (
    convert_to_paz_mod,
    detect_crimson_browser,
)


def _write(path: Path, content: bytes | str = b"") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        path.write_text(content, encoding="utf-8")
    else:
        path.write_bytes(content)


def _crimsonforge_manifest() -> dict:
    return {
        "format": "v1",
        "schema_version": 1,
        "kind": "mesh_loose_mod",
        "game": "Crimson Desert",
        "title": "Test Sword",
        "author": "Madao",
        "version": "1.0.0",
        "files_root": "files",
        "assets": [{
            "entry_path": "character/cd_phm_02_sword_0039.pac",
            "package_group": "0009",
            "format": "pac",
        }],
    }


def _synthesize_dragonslayer(root: Path) -> Path:
    """Build a minimal CrimsonForge-style mesh_loose_mod on disk."""
    mod = root / "Berserk -The DragonSlayer"
    _write(mod / "manifest.json", json.dumps(_crimsonforge_manifest()))
    _write(mod / "modinfo.json", json.dumps({"title": "Test Sword"}))
    _write(mod / "README.txt", "test")
    _write(mod / "files" / "character" / "cd_phm_02_sword_0039.pac",
           b"PAC_MESH_BODY")
    for name in (
        "cd_phm_02_sword_0039_disp.dds",
        "cd_phm_02_sword_0039_ma.dds",
        "cd_phm_02_sword_0039_mg.dds",
        "cd_phm_02_sword_0039_n.dds",
    ):
        _write(mod / "Tex" / "Character" / "texture" / name,
               b"DDS " + b"\x00" * 124 + b"RAWDATA")
    _write(mod / "Tex" / "Character" / "texture"
           / "cd_phm_02_sword_0039.pac.xml", b"<root/>")
    return mod


def test_cb_handler_detects_crimsonforge_manifest(tmp_path: Path) -> None:
    mod = _synthesize_dragonslayer(tmp_path)
    manifest = detect_crimson_browser(mod)
    assert manifest is not None, (
        "CB detector must accept CrimsonForge manifests (format=v1, "
        "kind=mesh_loose_mod) — they have files_root pointing at an "
        "existing dir so the detector's fallback clause should match")
    assert manifest["_base_dir"] == mod


def test_convert_walks_sibling_tex_directory(tmp_path: Path) -> None:
    """The core GH #28 regression: Tex/ siblings must reach the
    texture-overlay / PAMT-resolution pipeline. Before the fix, CDUMM
    called ``convert_to_paz_mod`` and only files under ``files/`` ever
    hit ``_resolve_files_to_directories`` or ``build_texture_overlay``
    — every DDS in ``Tex/Character/texture/`` was silently dropped."""
    mod = _synthesize_dragonslayer(tmp_path)
    manifest = detect_crimson_browser(mod)
    assert manifest is not None

    game_dir = tmp_path / "game"
    game_dir.mkdir()
    work_dir = tmp_path / "work"
    work_dir.mkdir()

    seen_dds: list[str] = []

    def fake_resolve(files, game_dir_arg):
        # Nothing resolves — simulate a minimal game_dir with no PAMTs.
        return {}, list(files)

    def fake_build_overlay(dds_entries, game_dir_arg, work_dir_arg):
        for virtual_path, _src in dds_entries:
            seen_dds.append(Path(virtual_path).name)
        return ("0036", len(dds_entries))

    with patch(
        "cdumm.engine.crimson_browser_handler._resolve_files_to_directories",
        side_effect=fake_resolve,
    ), patch(
        "cdumm.engine.texture_mod_handler.build_texture_overlay",
        side_effect=fake_build_overlay,
    ):
        result = convert_to_paz_mod(manifest, game_dir, work_dir)

    assert result is not None, (
        "convert_to_paz_mod returned None — the sibling Tex/ content "
        "wasn't enough to produce an output dir")
    assert sorted(seen_dds) == sorted([
        "cd_phm_02_sword_0039_disp.dds",
        "cd_phm_02_sword_0039_ma.dds",
        "cd_phm_02_sword_0039_mg.dds",
        "cd_phm_02_sword_0039_n.dds",
    ]), (
        "All 4 DDS files from Tex/Character/texture/ must reach "
        f"build_texture_overlay — saw {seen_dds}")


def test_convert_ignores_unknown_sibling_dirs(tmp_path: Path) -> None:
    """Safety: don't harvest content from random top-level dirs. Only
    ``tex``/``textures``/``texture`` (case-insensitive) count as texture
    sidecars. A sibling ``cache/`` or ``screenshots/`` must be left
    alone so we don't drag in unrelated files."""
    mod = _synthesize_dragonslayer(tmp_path)
    # Add a noise directory that looks nothing like a texture sidecar.
    _write(mod / "screenshots" / "preview.dds",
           b"DDS " + b"\x00" * 124)
    _write(mod / "cache" / "thumb.dds",
           b"DDS " + b"\x00" * 124)

    manifest = detect_crimson_browser(mod)
    assert manifest is not None

    game_dir = tmp_path / "game"
    game_dir.mkdir()
    work_dir = tmp_path / "work"
    work_dir.mkdir()

    seen: list[str] = []

    def fake_resolve(files, game_dir_arg):
        return {}, list(files)

    def fake_build_overlay(dds_entries, game_dir_arg, work_dir_arg):
        for virtual_path, _src in dds_entries:
            seen.append(Path(virtual_path).name)
        return ("0036", len(dds_entries))

    with patch(
        "cdumm.engine.crimson_browser_handler._resolve_files_to_directories",
        side_effect=fake_resolve,
    ), patch(
        "cdumm.engine.texture_mod_handler.build_texture_overlay",
        side_effect=fake_build_overlay,
    ):
        convert_to_paz_mod(manifest, game_dir, work_dir)

    # Only the 4 DDSes from Tex/ — nothing from screenshots/ or cache/.
    assert "preview.dds" not in seen
    assert "thumb.dds" not in seen
